# Generated by Django 3.2.5 on 2021-08-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EksiSozlukTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_id', models.TextField()),
                ('trend_name', models.TextField()),
                ('time_range', models.IntegerField()),
                ('trend_order', models.IntegerField()),
                ('trend_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EksiSozlukTrendDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_id', models.TextField()),
                ('trend_link', models.TextField()),
                ('trend_desc', models.TextField()),
            ],
        ),
    ]
